name: PublishDistribution

on:
  release:
    types: [published]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      # Download Publish.zip
      - name: Download Release
        uses: robinraju/release-downloader@v1.5
        with: 
          repository: "DGP-Studio/Snap.Hutao"
          latest: true
          fileName: "*.zip"
          out-file-path: ./release-download
          
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: ./release-download/
          

